/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projackgroup;

import java.io.File;
import java.io.FileWriter;
import java.util.Date;
import javax.swing.JOptionPane;

import java.io.IOException;

/**
 *
 * @author comzone
 */
public class HomeFrom extends javax.swing.JFrame {
    

    /**
     * Creates new form HomeFrom
     */
    public HomeFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Caffe = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Ep = new javax.swing.JLabel();
        Ac = new javax.swing.JLabel();
        Lt = new javax.swing.JLabel();
        Cpn = new javax.swing.JLabel();
        Gt = new javax.swing.JLabel();
        Tt = new javax.swing.JLabel();
        Cc = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pt_show = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        show2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ep1 = new javax.swing.JCheckBox();
        ac1 = new javax.swing.JCheckBox();
        te1 = new javax.swing.JCheckBox();
        cp1 = new javax.swing.JCheckBox();
        gt1 = new javax.swing.JCheckBox();
        tt1 = new javax.swing.JCheckBox();
        cc1 = new javax.swing.JCheckBox();
        ep2 = new javax.swing.JCheckBox();
        ep3 = new javax.swing.JCheckBox();
        ac2 = new javax.swing.JCheckBox();
        ac3 = new javax.swing.JCheckBox();
        te2 = new javax.swing.JCheckBox();
        te3 = new javax.swing.JCheckBox();
        cp2 = new javax.swing.JCheckBox();
        cp3 = new javax.swing.JCheckBox();
        gt2 = new javax.swing.JCheckBox();
        gt3 = new javax.swing.JCheckBox();
        tt2 = new javax.swing.JCheckBox();
        tt3 = new javax.swing.JCheckBox();
        cc2 = new javax.swing.JCheckBox();
        cc3 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Caffe.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        Caffe.setText("ยินดีต้องรับสู่ Coffe Store");
        getContentPane().add(Caffe);
        Caffe.setBounds(51, 11, 244, 43);

        jLabel2.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        jLabel2.setText("เมนู");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(51, 60, 38, 43);

        Ep.setText("Esspresso");
        getContentPane().add(Ep);
        Ep.setBounds(51, 143, 48, 14);

        Ac.setText("Americano");
        getContentPane().add(Ac);
        Ac.setBounds(51, 188, 52, 14);

        Lt.setText("Latte");
        getContentPane().add(Lt);
        Lt.setBounds(51, 234, 25, 14);

        Cpn.setText("Cappuccino");
        getContentPane().add(Cpn);
        Cpn.setBounds(51, 273, 56, 14);

        Gt.setText("GreenTea");
        getContentPane().add(Gt);
        Gt.setBounds(51, 317, 47, 14);

        Tt.setText("ThaiTea");
        getContentPane().add(Tt);
        Tt.setBounds(51, 359, 39, 14);

        Cc.setText("CoCoa");
        getContentPane().add(Cc);
        Cc.setBounds(51, 400, 32, 14);

        jLabel10.setText("Hot");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(156, 89, 17, 14);

        jLabel11.setText("Ice");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(241, 89, 15, 14);

        jLabel12.setText("Frappe");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(306, 89, 34, 14);

        jScrollPane1.setViewportView(pt_show);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(418, 60, 364, 379);

        jLabel3.setText("Price");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(523, 463, 24, 14);
        getContentPane().add(show2);
        show2.setBounds(615, 457, 0, 0);

        jButton1.setText("Payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(497, 505, 75, 23);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(590, 505, 59, 23);

        ep1.setText("35");
        getContentPane().add(ep1);
        ep1.setBounds(148, 139, 37, 23);

        ac1.setText("35");
        getContentPane().add(ac1);
        ac1.setBounds(148, 184, 37, 23);

        te1.setText("35");
        getContentPane().add(te1);
        te1.setBounds(148, 230, 37, 23);

        cp1.setText("35");
        getContentPane().add(cp1);
        cp1.setBounds(148, 269, 37, 23);

        gt1.setText("35");
        getContentPane().add(gt1);
        gt1.setBounds(148, 313, 37, 23);

        tt1.setText("35");
        getContentPane().add(tt1);
        tt1.setBounds(148, 355, 37, 23);

        cc1.setText("35");
        getContentPane().add(cc1);
        cc1.setBounds(148, 396, 37, 23);

        ep2.setText("35");
        getContentPane().add(ep2);
        ep2.setBounds(226, 139, 37, 23);

        ep3.setText("35");
        getContentPane().add(ep3);
        ep3.setBounds(303, 139, 37, 23);

        ac2.setText("35");
        getContentPane().add(ac2);
        ac2.setBounds(226, 184, 37, 23);

        ac3.setText("35");
        getContentPane().add(ac3);
        ac3.setBounds(303, 184, 37, 23);

        te2.setText("35");
        getContentPane().add(te2);
        te2.setBounds(226, 230, 37, 23);

        te3.setText("35");
        getContentPane().add(te3);
        te3.setBounds(303, 230, 37, 23);

        cp2.setText("35");
        getContentPane().add(cp2);
        cp2.setBounds(226, 269, 37, 23);

        cp3.setText("35");
        getContentPane().add(cp3);
        cp3.setBounds(303, 269, 37, 23);

        gt2.setText("35");
        getContentPane().add(gt2);
        gt2.setBounds(226, 313, 37, 23);

        gt3.setText("35");
        getContentPane().add(gt3);
        gt3.setBounds(303, 313, 37, 23);

        tt2.setText("35");
        getContentPane().add(tt2);
        tt2.setBounds(226, 355, 37, 23);

        tt3.setText("35");
        getContentPane().add(tt3);
        tt3.setBounds(303, 355, 37, 23);

        cc2.setText("35");
        getContentPane().add(cc2);
        cc2.setBounds(226, 396, 37, 23);

        cc3.setText("35");
        getContentPane().add(cc3);
        cc3.setBounds(303, 396, 37, 23);

        jLabel4.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel4.setText("บาท");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(659, 457, 21, 22);

        jButton3.setText("Receipt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(667, 505, 69, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:         
        Date date = new Date();
        String name = "";
        int money = 0;
        if(ep1.isSelected()==true){
        money = money+35;
        name += "Esspresso(hot)                35\n";
        }
        if(ep2.isSelected()==true){
        money = money+45;
        name += "Esspresso(ice)                45\n";
        }
        if(ep3.isSelected()==true){
        money = money+50;
        name += "Esspresso(Frappe)             50\n";
        }
        if(ac1.isSelected()==true){
        money = money+35;
        name += "Americano(hot)                35\n";
        }
        if(ac2.isSelected()==true){
        money = money+45;
        name += "Americano(ice)                45\n";
        }
        if(ac3.isSelected()==true){
        money = money+50;
        name += "Americano(Frappe)             50\n";
        }
         if(te1.isSelected()==true){
        money = money+35;
        name += "Tate(hot)                     35\n";
        }
          if(te2.isSelected()==true){
        money = money+45;
        name += "Tate(ice)                     45\n";
        }
          if(te3.isSelected()==true){
        money = money+50;
        name += "Tate(Frappe)                  50\n";
        }
          if(cp1.isSelected()==true){
        money = money+35;
        name += "Capuccino(hot)                35\n";
        }
          if(cp2.isSelected()==true){
        money = money+45;
        name += "Capuccino(ice)                45\n";
        }
          if(cp3.isSelected()==true){
        money = money+50;
        name += "Capuccino(Freappe)            50\n";
        }
          if(gt1.isSelected()==true){
        money = money+35;
        name += "Greentea(hot)                 35\n";
        }
          if(gt2.isSelected()==true){
        money = money+45;
        name += "Greentea(ice)                 45\n";
        }
          if(gt3.isSelected()==true){
        money = money+50;
        name += "Greentea(Freappe)             50\n";
        }
          if(tt1.isSelected()==true){
        money = money+35;
        name += "Thaitea(hot)                  35\n";
        }
          if(tt2.isSelected()==true){
        money = money+45;
        name += "Thaitea(ice)                  45\n";
        }
          if(tt3.isSelected()==true){
        money = money+50;
        name += "Thaitea(Freappe)              50\n";
        }
          if(cc1.isSelected()==true){
        money = money+35;
        name += "Coco(hot)                     35\n";
        }
          if(cc2.isSelected()==true){
        money = money+45;
        name += "Coco(ice)                     45\n";
        }
          if(cc3.isSelected()==true){
        money = money+50;
        name += "Coco(Freappe)                 50\n";
        }
          
          pt_show.setText("Caffe Store" + " Wellcome " + "\t\n\t\n" + name + "Total :" + money+ " Bath " +"\t\n\t\n "+ "Date : " + date.toString()+"\t\n\t\n" +"Save : C:\\Users\\comzone\\Downloads\\Receipt.txt. ");
          show2.setText(String.valueOf(money));
          

          
                                               
                    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        pt_show.setText("  ");
        show2.setText("   ");
        ep1.setSelected(false);
        ep2.setSelected(false);
        ep3.setSelected(false);
        ac1.setSelected(false);
        ac2.setSelected(false);
        ac3.setSelected(false);
        te1.setSelected(false);
        te2.setSelected(false);
        te3.setSelected(false);
        cp1.setSelected(false);
        cp2.setSelected(false);
        cp3.setSelected(false);
        gt1.setSelected(false);
        gt2.setSelected(false);
        gt3.setSelected(false);
        tt1.setSelected(false);
        tt2.setSelected(false);
        tt3.setSelected(false);
        cc1.setSelected(false);
        cc2.setSelected(false);
        cc3.setSelected(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String path = "C:\\Users\\comzone\\Downloads\\Receipt.txt";
        File file = new File(path);
        FileWriter writer;
        try {
           writer = new FileWriter(file,true);
           writer.write(pt_show.getText());
           writer.close();
           
           System.out.println("Write success!");           
        }catch (IOException e) {
          e.printStackTrace();        
        }
        
  
      
        JOptionPane.showMessageDialog(null,pt_show);
       
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ac;
    private javax.swing.JLabel Caffe;
    private javax.swing.JLabel Cc;
    private javax.swing.JLabel Cpn;
    private javax.swing.JLabel Ep;
    private javax.swing.JLabel Gt;
    private javax.swing.JLabel Lt;
    private javax.swing.JLabel Tt;
    private javax.swing.JCheckBox ac1;
    private javax.swing.JCheckBox ac2;
    private javax.swing.JCheckBox ac3;
    private javax.swing.JCheckBox cc1;
    private javax.swing.JCheckBox cc2;
    private javax.swing.JCheckBox cc3;
    private javax.swing.JCheckBox cp1;
    private javax.swing.JCheckBox cp2;
    private javax.swing.JCheckBox cp3;
    private javax.swing.JCheckBox ep1;
    private javax.swing.JCheckBox ep2;
    private javax.swing.JCheckBox ep3;
    private javax.swing.JCheckBox gt1;
    private javax.swing.JCheckBox gt2;
    private javax.swing.JCheckBox gt3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane pt_show;
    private javax.swing.JLabel show2;
    private javax.swing.JCheckBox te1;
    private javax.swing.JCheckBox te2;
    private javax.swing.JCheckBox te3;
    private javax.swing.JCheckBox tt1;
    private javax.swing.JCheckBox tt2;
    private javax.swing.JCheckBox tt3;
    // End of variables declaration//GEN-END:variables
}
